### ISSUE TITLE
is it compatible with server side rendering?

### ISSUE THREAD

**Issue by ThomasChoii** [aceHubert/material-ui-slider#3]
`/Users/thomas.choi/code/ssr_section2/react-server-side/node_modules/material-ui-slider/dist/npm/es5/index.js:1
(function (exports, require, module, __filename, __dirname) { export * from './src';
                                                              ^^^^^^

SyntaxError: Unexpected token export`

I keep getting this issue

**Comment by aceHubert** [comment]
more details, please.

**Comment by patcito** [comment]
I have the same issue. Here's a repo to reproduce the error https://github.com/patcito/material-ui-next-slider (just run yarn and then npm run dev).

The error I'm getting is:

https://gist.github.com/patcito/84f6404abc93a861f1386cbd4b397f62

and on the terminal:

/home/pat/repos/material-ui-next-slider/node_modules/material-ui-slider/dist/npm/es5/index.js:1                                                                      
(function (exports, require, module, __filename, __dirname) { export * from './src';                                                                                  
                                                              ^^^^^^                                                                                                  
                                                                                                                                                                      
SyntaxError: Unexpected token export                                                                                                                                  
    at new Script (vm.js:74:7)                                                                                                                                        
    at createScript (vm.js:246:10)                                                                                                                                    
    at Object.runInThisContext (vm.js:298:10)                                                                                                                         
    at Module._compile (internal/modules/cjs/loader.js:657:28)                                                                                                        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)                                                                                          
    at Module.load (internal/modules/cjs/loader.js:599:32)                                                                                                            
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)                                                                                                          
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)                                                                                                   
    at Module.require (internal/modules/cjs/loader.js:637:17)                                                                                                         
    at require (internal/modules/cjs/helpers.js:20:18)                                                                                                                
    at Object.material-ui-slider (/home/plpp/repos/material-ui-next-slider/.next/server/static/development/pages/index.js:594:18)                                     
    at __webpack_require__ (/home/plpp/repos/material-ui-next-slider/.next/server/static/development/pages/index.js:23:31)                                            
    at Module../pages/index.js (/home/plpp/repos/material-ui-next-slider/.next/server/static/development/pages/index.js:400:76)                                       
    at __webpack_require__ (/home/plpp/repos/material-ui-next-slider/.next/server/static/development/pages/index.js:23:31)                                            
    at Object.3 (/home/plpp/repos/material-ui-next-slider/.next/server/static/development/pages/index.js:582:18)                                                      
    at __webpack_require__ (/home/plpp/repos/material-ui-next-slider/.next/server/static/development/pages/index.js:23:31)                                            
/home/plpp/repos/material-ui-next-slider/node_modules/material-ui-slider/dist/npm/es5/index.js:1                                                                      
(function (exports, require, module, __filename, __dirname) { export * from './src';                                                                                  
                                                              ^^^^^^                                                                                                  
                                        
Hope this helps.

**Comment by pantharshit00** [comment]
@patcito I resolved this using `next-plugin-transpile-modules` plugin.
